apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.name }}
  labels:
    {{- include "aria2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui_service.type }}
  ports:
    - port: {{ .Values.ui_service.port }}
      targetPort: {{ .Values.ui_service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "aria2.selectorLabels" . | nindent 4 }}
