apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudreve.fullname" . }}
  namespace: {{ include "cloudreve.namespace" . }}
  labels:
    {{- include "cloudreve.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cloudreve.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cloudreve.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cloudreve.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.podPortName }}
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: "/cloudreve/conf.ini"
              subPath: conf.ini
            - name: storage
              mountPath: "/data"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "cloudreve.fullname" . }}
        {{- if and .Values.persistence.enabled (eq .Values.persistence.type "pvc") }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ tpl (.Values.persistence.existingClaim | default (include "cloudreve.fullname" .)) . }}
        {{- else}}
        - name: storage
          {{- if .Values.persistence.inMemory.enabled }}
          emptyDir:
            medium: Memory
            {{- with .Values.persistence.inMemory.sizeLimit }}
            sizeLimit: {{ . }}
            {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}


