{{- if .Values.createConfigFile.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alist.fullname" . }}
  namespace: {{ include "alist.namespace" . }}
  labels:
    {{- include "alist.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.json: |
    {{ toJson .Values.config }}
{{- end }}