apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alist.fullname" . }}
  namespace: {{ include "alist.namespace" . }}
  labels:
    {{- include "alist.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "alist.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "alist.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "alist.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.createConfigFile.enabled }}
      initContainers:
        - name: init-config
          image: "{{ .Values.createConfigFile.image.repository }}:{{ .Values.createConfigFile.image.tag }}"
          imagePullPolicy: {{ .Values.createConfigFile.image.pullPolicy }}
          command:
            # - ["/bin/sh", "-c", "cp /config.json /data/config.json"]
            - cp
            - /config.json
            - /data/config.json
          volumeMounts:
            - name: config
              mountPath: "/config.json"
              subPath: config.json
            - name: storage
              mountPath: "/data"
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.podPortName }}
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          volumeMounts:
            - name: storage
              mountPath: "/opt/alist/data"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.createConfigFile.enabled }}
        - name: config
          configMap:
            name: {{ include "alist.fullname" . }}
        {{- end}}
        {{- if and .Values.persistence.enabled (eq .Values.persistence.type "pvc") }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ tpl (.Values.persistence.existingClaim | default (include "alist.fullname" .)) . }}
        {{- else }}
        - name: storage
          {{- if .Values.persistence.inMemory.enabled }}
          emptyDir:
            medium: Memory
            {{- with .Values.persistence.inMemory.sizeLimit }}
            sizeLimit: {{ . }}
            {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}


